name: CI

on: [push, pull_request]

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: typst-cli

      - name: Install Pandoc
        shell: bash
        run: |
          sudo apt get install -y pandoc

      - name: Show version information
        shell: bash
        run: |
          pandoc --version
          typst --version

      - name: Run tests
        run: just check
