name: Release

on:
  push:
    tags:
      - "v*"

env:
  APP_NAME: easy_rust

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # it is a must!
          fetch-depth: 0

      - name: Set the release version
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}

      - name: Checkout current tag
        shell: bash
        run: |
          git checkout v${{ env.RELEASE_VERSION }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .cliff.toml
          args: -vv --strip header --current
        env:
          OUTPUT: CHANGELOG.md.tmp

      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: "v${{ env.RELEASE_VERSION }}"
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
          body_path: "${{ steps.git-cliff.outputs.changelog }}"

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set the release version
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}

      - uses: taiki-e/install-action@v2
        with:
          tool: just, typst-cli

      - name: Install Pandoc
        shell: bash
        run: |
          sudo apt-get install -y pandoc

      - name: Build
        run: just compile

      - name: Build archive
        shell: bash
        run: |
          outdir="./build"

          echo "PDF=$outdir/easy-rust.pdf" >> $GITHUB_ENV
          echo "EPUB=$outdir/easy-rust.epub" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: |
            ${{ env.PDF }}
            ${{ env.EPUB }}
